[project]
name = "command-actor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "paramiko>=3.5.1",
    "pyinstaller>=6.12.0",
]
